config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index" # this make home/index as our homepage
  get "/:room_name" => "home#room" # this make home/room as our homepage
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  # root 'inertia_example#index' # this make home/index as our homepage
  # resources :messages # will be used for chat application form.
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    chatRooms = ChatChannel::CHATROOMS.keys
    render inertia: 'Index', props: {
      room_names: chatRooms,
    }
  end

  def room()
    room_name = params[:room_name]
    name = params[:name]
    id = params[:id]
    render inertia: 'Room', props: {
      room_name: room_name,
      name: name,
      id: id,
    }
  end
end

app/controllers/inertia_example_controller.rb
# frozen_string_literal: true
require 'securerandom'

class InertiaExampleController < ApplicationController
  def index
    chatRooms = ChatChannel::CHATROOMS.keys
    render inertia: 'InertiaExample', props: {
      name: params.fetch(:name, 'Bro'),
    }
  end

  def room()
    room_name = params[:room_name]
    render inertia: 'Room', props: {
      room_name: room_name,
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div style="text-align: center;" id="app">
  renderable by react
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title inertia><%= content_for(:title) || "Socket App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>

    <%= inertia_ssr_head %>
    <%= vite_client_tag if Rails.env.development? %> <!-- Only include HMR client in development -->
    <%= vite_stylesheet_tag 'application' %>
    <%= vite_javascript_tag 'application' %>
    <%= vite_typescript_tag 'inertia' %>
    <%= vite_react_refresh_tag %>
    <!--
      If using a TypeScript entrypoint file:
        vite_typescript_tag 'application'

      If using a .jsx or .tsx entrypoint, add the extension:
        vite_javascript_tag 'application.jsx'

      Visit the guide for more information: https://vite-ruby.netlify.app/guide/rails
    -->

  </head>

  <body style="background-color: #f9fafb;">
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<p><%= message.body %></p>